services:
    xxl-job:
        image: openjdk:21-jdk-slim-v1
        container_name: xxl-job-dipatcher
        hostname: xxl-job-dipatcher.jukit.loc
        ports:
            - "8080:8080"
        volumes:
            - "./data/:/data/"
            - "./m2/:/root/.m2"
            - "~/opt/disk/java/jukit-xxl-job/:/app/"
        networks:
            - app_net
        working_dir: /app/
        restart: always
        stdin_open: true
        tty: true
        extra_hosts:
            - "local.host:127.0.0.1"
        environment:
            # job admin
            XXL_JOB_SPRING_ACTIVE: dev
            XXL_JOB_MYSQL_HOST: 115.190.154.216
            XXL_JOB_MYSQL_PORT: 3306
            XXL_JOB_MYSQL_USERNAME: root
            XXL_JOB_MYSQL_PASSWORD: RTyFCA0Zr48ciRH8x5hBxAR5zflqmY82
            XXL_JOB_TOKEN: dZS52x1rpqKRct3LfE2MyrZ5G69Nkj11
            XXL_JOB_LOG_HOME: /data/applogs
            XXL_JOB_ADMIN_ADDRESS: http://127.0.0.1:8080
        # #command: java -jar target/dataclean-0.0.1-SNAPSHOT.jar --spring.profiles.active=prod
        command: sh
networks:
  app_net:
    external: true
